### ISSUE TITLE
Fast sampling get worse PSNR

### ISSUE THREAD

**Issue by yuanzhi-zhu** [AlexiaJM/score_sde_fast_sampling#5]
Hi Alexia,
Thanks for your constructive work on score-based models.

I create this issue also because I met several problems when implementing it:

- When I use your _AdaptivePredictor_ from [sde_sampling_torch.py](https://github.com/AlexiaJM/score_sde_fast_sampling/blob/main/sde_sampling_torch.py) for task like Super Resolution (e.g. [SR3](https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement)), I get a much worse PSNR (from 32dB to 22dB).

    - Is this expected? It seems that skip steps when sampling always introduce large errors which hurt PSNR.

    - This error seems to be bigger when the image size increase? I got unsatisfying images from a pretrained (VE) model for generating Monet paint (256*256), but I guess maybe I have to take care with some hyper-parameters :)

- This _AdaptivePredictor_ is a improved solver for the reverse SDE, if my understanding is correct. In this case, could we use a corrector to correct the errors from last question? (I tried with 1 step corrector along with each AdaptivePredictor and the PSNR is improved to 25dB) Have you done experiment with a corrector, or you find that the it not worthy since it slow down the sampling significantly?

**Comment by yuanzhi-zhu** [comment]
**Supplement:**

I would like to provide one possible reason for the low PSNR generated by this fast sampling.

I recorded the time $t \in [0,T]$ for each step of the solver, and generate a plot for visualization (four lines represent four samples I traced in a batch) as following:

![plot](https://user-images.githubusercontent.com/24802044/189336957-00eb4097-b4cd-4fb3-acd1-e8f363077ecf.png)

It shows that the step_size is constant in the beginning (linear decreasing), and getting bigger and bigger closer to the end.

Since when it's close to the end, we have small noise-levels, this indicates that the this adaptive solver does not pay much attention for the small noise denoising part of sampling as described in this paper https://arxiv.org/abs/2206.00070v1 (and eventually we get low PSNR).

**Comment by AlexiaJM** [comment]
Hi Yuanzhi,

It should not be worse. I have not done any super-resolution so the parameters may need to be changed. Optimal results with high-res are here: https://github.com/AlexiaJM/score_sde_fast_sampling/blob/5da8f3fe103ee5ac3c3a336f16cc06c9541f0ed9/experiments.sh#L170. We uses config.sampling.abstol=2/256=0.0078 and config.sampling.reltol=1e-2 when x in [-1,1], or config.sampling.abstol=1/256=0.0039 and config.sampling.reltol=1e-2 when x in [0,1]. abstol shouldn't need to change, but you can try changing reltol, lower values will take more steps and increase quality. If that still doesn't fix the problem, as a last resort you can tune 'exp', maybe 0.5 or 1.

I have not tried with the corrector because it increases sampling time, but feel free to use if it helps.

With VE, the step-size will increase over time as the discretisation error of the SDE is very large in the beginning but decreases over time, hence why it must slow down early and speed it later. Its all about solving the SDE with as little error as possible, while going fast.

**Comment by yuanzhi-zhu** [comment]
Thank you so much for fast reply :)

Maybe I should try to tune these hyperparameter more. 

But by worse I did not mean the visual quality, i.e. PSNR is naturally against scores like FID. I was just surprised to get the PSNR lower than my expectation 😃
